const countries = [
    { code: '+93', name: 'Afghanistan', flagUrl: 'https://flagcdn.com/w40/af.png' },
    { code: '+355', name: 'Albania', flagUrl: 'https://flagcdn.com/w40/al.png' },
    { code: '+213', name: 'Algeria', flagUrl: 'https://flagcdn.com/w40/dz.png' },
    { code: '+1-684', name: 'Andora', flagUrl: 'https://flagcdn.com/w40/ao.png' },
    { code: '+1-684', name: 'Angola', flagUrl: 'https://flagcdn.com/w40/ai.png' },
    { code: '+1-684', name: 'Anguilla', flagUrl: 'https://flagcdn.com/w40/ai.png' },
    { code: '+1-684', name: 'Antarctica', flagUrl: 'https://flagcdn.com/w40/ai.png' },
    { code: '+1-684', name: 'Antigua and Barbuda', flagUrl: 'https://flagcdn.com/w40/ai.png' },
    { code: '+54', name: 'Argentina', flagUrl: 'https://flagcdn.com/w40/ar.png' },
    { code: '+54', name: 'Armenia', flagUrl: 'https://flagcdn.com/w40/ar.png' },
    { code: '+54', name: 'Aruba', flagUrl: 'https://flagcdn.com/w40/ar.png' },
    { code: '+61', name: 'Australia', flagUrl: 'https://flagcdn.com/w40/au.png' },
    { code: '+61', name: 'Austria', flagUrl: 'https://flagcdn.com/w40/au.png' },
    { code: '+61', name: 'Azerbaijan', flagUrl: 'https://flagcdn.com/w40/au.png' },
    { code: '+61', name: 'Bahamas', flagUrl: 'https://flagcdn.com/w40/au.png' },
    { code: '+61', name: 'Bahrain', flagUrl: 'https://flagcdn.com/w40/au.png' },
    { code: '+880', name: 'Bangladesh', flagUrl: 'https://flagcdn.com/w40/bd.png' },
    { code: '+591', name: 'Barbados', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Belarus', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Belgium', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Belize', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Benin', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Bermuda', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Bhutan', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Bolivia', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Bosnia and Herzegovina', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Botswana', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+55', name: 'Brazil', flagUrl: 'https://flagcdn.com/w40/br.png' },
    { code: '+591', name: 'British Indian Ocean Territory', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'British Virgin Islands', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Brunei', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Bulgaria', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Burkina Faso', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+591', name: 'Barundi', flagUrl: 'https://flagcdn.com/w40/bo.png' },
    { code: '+1', name: 'Combodia', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Cameroon', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Canada', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Cape Verde', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Cayman Islands', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Central African Republic', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Chad', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+1', name: 'Chile', flagUrl: 'https://flagcdn.com/w40/ca.png' },
    { code: '+86', name: 'China', flagUrl: 'https://flagcdn.com/w40/cn.png' },
    { code: '+', name: 'Christmas Island', flagUrl: 'https://flagcdn.com/w40/cx.png' },
    { code: '+', name: 'Cocos Islands', flagUrl: 'https://flagcdn.com/w40/cc.png' },
    { code: '+', name: 'Colombia', flagUrl: 'https://flagcdn.com/w40/co.png' },
    { code: '+', name: 'Comoros', flagUrl: 'https://flagcdn.com/w40/km.png' },
    { code: '+', name: 'Cook Islands', flagUrl: 'https://flagcdn.com/w40/ck.png' },
    { code: '+', name: 'Costa Rica', flagUrl: 'https://flagcdn.com/w40/cr.png' },
    { code: '+', name: 'Croatia', flagUrl: 'https://flagcdn.com/w40/hr.png' },
    { code: '+', name: 'Cuba', flagUrl: 'https://flagcdn.com/w40/cu.png' },
    { code: '+', name: 'Curacao', flagUrl: 'https://flagcdn.com/w40/cw.png' },
    { code: '+', name: 'Cyprus', flagUrl: 'https://flagcdn.com/w40/cy.png' },
    { code: '+', name: 'Czech Republic', flagUrl: 'https://flagcdn.com/w40/cz.png' },
    { code: '+', name: 'Democratic Republic of the Congo', flagUrl: 'https://flagcdn.com/w40/cd.png' },
    { code: '+', name: 'Denmark', flagUrl: 'https://flagcdn.com/w40/dk.png' },
    { code: '+', name: 'Djibouti', flagUrl: 'https://flagcdn.com/w40/dj.png' },
    { code: '+', name: 'Dominica', flagUrl: 'https://flagcdn.com/w40/dm.png' },
    { code: '+', name: 'East Timor', flagUrl: 'https://flagcdn.com/w40/tl.png' },
    { code: '+', name: 'Ecuador', flagUrl: 'https://flagcdn.com/w40/ec.png' },
    { code: '+', name: 'Egypt', flagUrl: 'https://flagcdn.com/w40/eg.png' },
    { code: '+', name: 'El Salvador', flagUrl: 'https://flagcdn.com/w40/sv.png' },
    { code: '+', name: 'Equatorial Guinea', flagUrl: 'https://flagcdn.com/w40/gq.png' },
    { code: '+', name: 'Eritrea', flagUrl: 'https://flagcdn.com/w40/er.png' },
    { code: '+', name: 'Estonia', flagUrl: 'https://flagcdn.com/w40/ee.png' },
    { code: '+', name: 'Ethiopia', flagUrl: 'https://flagcdn.com/w40/et.png' },
    { code: '+', name: 'Falkland Islands', flagUrl: 'https://flagcdn.com/w40/fk.png' },
    { code: '+', name: 'Faroe Islands', flagUrl: 'https://flagcdn.com/w40/fo.png' },
    { code: '+', name: 'Fiji', flagUrl: 'https://flagcdn.com/w40/fj.png' },
    { code: '+', name: 'Finland', flagUrl: 'https://flagcdn.com/w40/fi.png' },
    { code: '+', name: 'France', flagUrl: 'https://flagcdn.com/w40/fr.png' },
    { code: '+', name: 'French Polynesia', flagUrl: 'https://flagcdn.com/w40/pf.png' },
    { code: '+', name: 'Gabon', flagUrl: 'https://flagcdn.com/w40/ga.png' },
    { code: '+', name: 'Gambia', flagUrl: 'https://flagcdn.com/w40/gm.png' },
    { code: '+', name: 'Georgia', flagUrl: 'https://flagcdn.com/w40/ge.png' },
    { code: '+', name: 'Germany', flagUrl: 'https://flagcdn.com/w40/de.png' },
    { code: '+', name: 'Ghana', flagUrl: 'https://flagcdn.com/w40/gh.png' },
    { code: '+', name: 'Gibraltar', flagUrl: 'https://flagcdn.com/w40/gi.png' },
    { code: '+', name: 'Greece', flagUrl: 'https://flagcdn.com/w40/gr.png' },
    { code: '+', name: 'Greenland', flagUrl: 'https://flagcdn.com/w40/gl.png' },
    { code: '+', name: 'Grenada', flagUrl: 'https://flagcdn.com/w40/gd.png' },
    { code: '+', name: 'Guam', flagUrl: 'https://flagcdn.com/w40/gu.png' },
    { code: '+', name: 'Guatemala', flagUrl: 'https://flagcdn.com/w40/gt.png' },
    { code: '+', name: 'Guernsey', flagUrl: 'https://flagcdn.com/w40/gg.png' },
    { code: '+', name: 'Guinea', flagUrl: 'https://flagcdn.com/w40/gn.png' },
    { code: '+', name: 'Guinea-Bissau', flagUrl: 'https://flagcdn.com/w40/gw.png' },
    { code: '+', name: 'Haiti', flagUrl: 'https://flagcdn.com/w40/ht.png' },
    { code: '+', name: 'Honduras', flagUrl: 'https://flagcdn.com/w40/hn.png' },
    { code: '+', name: 'Hong Kong', flagUrl: 'https://flagcdn.com/w40/hk.png' },
    { code: '+', name: 'Hungary', flagUrl: 'https://flagcdn.com/w40/hu.png' },
    { code: '+', name: 'Iceland', flagUrl: 'https://flagcdn.com/w40/is.png' },
    { code: '+', name: 'India', flagUrl: 'https://flagcdn.com/w40/in.png' },
    { code: '+', name: 'Indonesia', flagUrl: 'https://flagcdn.com/w40/id.png' },
    { code: '+', name: 'Iran', flagUrl: 'https://flagcdn.com/w40/ir.png' },
    { code: '+', name: 'Iraq', flagUrl: 'https://flagcdn.com/w40/iq.png' },
    { code: '+', name: 'Ireland', flagUrl: 'https://flagcdn.com/w40/ie.png' },
    { code: '+', name: 'Isle of Man', flagUrl: 'https://flagcdn.com/w40/im.png' },
    { code: '+', name: 'Israel', flagUrl: 'https://flagcdn.com/w40/il.png' },
    { code: '+', name: 'Italy', flagUrl: 'https://flagcdn.com/w40/it.png' },
    { code: '+', name: 'Ivory Coast', flagUrl: 'https://flagcdn.com/w40/ci.png' },
    { code: '+', name: 'Jamaica', flagUrl: 'https://flagcdn.com/w40/jm.png' },
    { code: '+', name: 'Japan', flagUrl: 'https://flagcdn.com/w40/jp.png' },
    { code: '+', name: 'Jersey', flagUrl: 'https://flagcdn.com/w40/je.png' },
    { code: '+', name: 'Jordan', flagUrl: 'https://flagcdn.com/w40/jo.png' },
    { code: '+', name: 'Kazakhstan', flagUrl: 'https://flagcdn.com/w40/kz.png' },
    { code: '+', name: 'Kenya', flagUrl: 'https://flagcdn.com/w40/ke.png' },
    { code: '+', name: 'Kiribati', flagUrl: 'https://flagcdn.com/w40/ki.png' },
    { code: '+', name: 'Kosovo', flagUrl: 'https://flagcdn.com/w40/xk.png' },
    { code: '+', name: 'Kuwait', flagUrl: 'https://flagcdn.com/w40/kw.png' },
    { code: '+', name: 'Kyrgyzstan', flagUrl: 'https://flagcdn.com/w40/kg.png' },
    { code: '+', name: 'Laos', flagUrl: 'https://flagcdn.com/w40/la.png' },
    { code: '+', name: 'Latvia', flagUrl: 'https://flagcdn.com/w40/lv.png' },
    { code: '+', name: 'Lebanon', flagUrl: 'https://flagcdn.com/w40/lb.png' },
    { code: '+', name: 'Lesotho', flagUrl: 'https://flagcdn.com/w40/ls.png' },
    { code: '+', name: 'Liberia', flagUrl: 'https://flagcdn.com/w40/lr.png' },
    { code: '+', name: 'Libya', flagUrl: 'https://flagcdn.com/w40/ly.png' },
    { code: '+', name: 'Liechtenstein', flagUrl: 'https://flagcdn.com/w40/li.png' },
    { code: '+', name: 'Lithuania', flagUrl: 'https://flagcdn.com/w40/lt.png' },
    { code: '+', name: 'Macau', flagUrl: 'https://flagcdn.com/w40/mo.png' },
    { code: '+', name: 'Macedonia', flagUrl: 'https://flagcdn.com/w40/mk.png' },
    { code: '+', name: 'Madagascar', flagUrl: 'https://flagcdn.com/w40/mg.png' },
    { code: '+', name: 'Malawi', flagUrl: 'https://flagcdn.com/w40/mw.png' },
    { code: '+', name: 'Malaysia', flagUrl: 'https://flagcdn.com/w40/my.png' },
    { code: '+', name: 'Maldives', flagUrl: 'https://flagcdn.com/w40/mv.png' },
    { code: '+', name: 'Mali', flagUrl: 'https://flagcdn.com/w40/ml.png' },
    { code: '+', name: 'Malta', flagUrl: 'https://flagcdn.com/w40/mt.png' },
    { code: '+', name: 'Marshall Islands', flagUrl: 'https://flagcdn.com/w40/mh.png' },
    { code: '+', name: 'Mauritania', flagUrl: 'https://flagcdn.com/w40/mr.png' },
    { code: '+', name: 'Mauritius', flagUrl: 'https://flagcdn.com/w40/mu.png' },
    { code: '+', name: 'Mayotte', flagUrl: 'https://flagcdn.com/w40/yt.png' },
    { code: '+', name: 'Mexico', flagUrl: 'https://flagcdn.com/w40/mx.png' },
    { code: '+', name: 'Micronesia', flagUrl: 'https://flagcdn.com/w40/fm.png' },
    { code: '+', name: 'Moldova', flagUrl: 'https://flagcdn.com/w40/md.png' },
    { code: '+', name: 'Monaco', flagUrl: 'https://flagcdn.com/w40/mc.png' },
    { code: '+', name: 'Mongolia', flagUrl: 'https://flagcdn.com/w40/mn.png' },
    { code: '+', name: 'Montenegro', flagUrl: 'https://flagcdn.com/w40/me.png' },
    { code: '+', name: 'Montserrat', flagUrl: 'https://flagcdn.com/w40/ms.png' },
    { code: '+', name: 'Morocco', flagUrl: 'https://flagcdn.com/w40/ma.png' },
    { code: '+', name: 'Mozambique', flagUrl: 'https://flagcdn.com/w40/mz.png' },
    { code: '+', name: 'Myanmar', flagUrl: 'https://flagcdn.com/w40/mm.png' },
    { code: '+', name: 'Namibia', flagUrl: 'https://flagcdn.com/w40/na.png' },
    { code: '+', name: 'Nauru', flagUrl: 'https://flagcdn.com/w40/nr.png' },
    { code: '+', name: 'Nepal', flagUrl: 'https://flagcdn.com/w40/np.png' },
    { code: '+', name: 'Netherlands', flagUrl: 'https://flagcdn.com/w40/nl.png' },
    { code: '+', name: 'Netherlands Antilles', flagUrl: 'https://flagcdn.com/w40/an.png' },
    { code: '+', name: 'New Caledonia', flagUrl: 'https://flagcdn.com/w40/nc.png' },
    { code: '+', name: 'New Zealand', flagUrl: 'https://flagcdn.com/w40/nz.png' },
    { code: '+', name: 'Nicaragua', flagUrl: 'https://flagcdn.com/w40/ni.png' },
    { code: '+', name: 'Niger', flagUrl: 'https://flagcdn.com/w40/ne.png' },
    { code: '+', name: 'Nigeria', flagUrl: 'https://flagcdn.com/w40/ng.png' },
    { code: '+', name: 'Niue', flagUrl: 'https://flagcdn.com/w40/nu.png' },
    { code: '+', name: 'North Korea', flagUrl: 'https://flagcdn.com/w40/kp.png' },
    { code: '+', name: 'Northern Mariana Islands', flagUrl: 'https://flagcdn.com/w40/mp.png' },
    { code: '+', name: 'Norway', flagUrl: 'https://flagcdn.com/w40/no.png' },
    { code: '+', name: 'Pakistan', flagUrl: 'https://flagcdn.com/w40/pk.png' },
    { code: '+', name: 'Palau', flagUrl: 'https://flagcdn.com/w40/pw.png' },
    { code: '+', name: 'Palestine', flagUrl: 'https://flagcdn.com/w40/ps.png' },
    { code: '+', name: 'Panama', flagUrl: 'https://flagcdn.com/w40/pa.png' },
    { code: '+', name: 'Papua New Guinea', flagUrl: 'https://flagcdn.com/w40/pg.png' },
    { code: '+', name: 'Paraguay', flagUrl: 'https://flagcdn.com/w40/py.png' },
    { code: '+', name: 'Peru', flagUrl: 'https://flagcdn.com/w40/pe.png' },
    { code: '+', name: 'Philippines', flagUrl: 'https://flagcdn.com/w40/ph.png' },
    { code: '+', name: 'Pitcairn', flagUrl: 'https://flagcdn.com/w40/pn.png' },
    { code: '+', name: 'Poland', flagUrl: 'https://flagcdn.com/w40/pl.png' },
    { code: '+', name: 'Portugal', flagUrl: 'https://flagcdn.com/w40/pt.png' },
    { code: '+', name: 'Puerto Rico', flagUrl: 'https://flagcdn.com/w40/pr.png' },
    { code: '+', name: 'Qatar', flagUrl: 'https://flagcdn.com/w40/qa.png' },
    { code: '+', name: 'Republic of the Congo', flagUrl: 'https://flagcdn.com/w40/cg.png' },
    { code: '+', name: 'Reunion', flagUrl: 'https://flagcdn.com/w40/re.png' },
    { code: '+', name: 'Romania', flagUrl: 'https://flagcdn.com/w40/ro.png' },
    { code: '+', name: 'Russia', flagUrl: 'https://flagcdn.com/w40/ru.png' },
    { code: '+', name: 'Rwanda', flagUrl: 'https://flagcdn.com/w40/rw.png' },
    { code: '+', name: 'Saint Barthelemy', flagUrl: 'https://flagcdn.com/w40/bl.png' },
    { code: '+', name: 'Saint Helena', flagUrl: 'https://flagcdn.com/w40/sh.png' },
    { code: '+', name: 'Saint Kitts and Nevis', flagUrl: 'https://flagcdn.com/w40/kn.png' },
    { code: '+', name: 'Saint Lucia', flagUrl: 'https://flagcdn.com/w40/lc.png' },
    { code: '+', name: 'Saint Martin', flagUrl: 'https://flagcdn.com/w40/mf.png' },
    { code: '+', name: 'Saint Pierre and Miquelon', flagUrl: 'https://flagcdn.com/w40/pm.png' },
    { code: '+', name: 'Saint Vincent and the Grenadines', flagUrl: 'https://flagcdn.com/w40/vc.png' },
    { code: '+', name: 'Samoa', flagUrl: 'https://flagcdn.com/w40/ws.png' },
    { code: '+', name: 'San Marino', flagUrl: 'https://flagcdn.com/w40/sm.png' },
    { code: '+', name: 'Sao Tome and Principe', flagUrl: 'https://flagcdn.com/w40/st.png' },
    { code: '+', name: 'Saudi Arabia', flagUrl: 'https://flagcdn.com/w40/sa.png' },
    { code: '+', name: 'Senegal', flagUrl: 'https://flagcdn.com/w40/sn.png' },
    { code: '+', name: 'Serbia', flagUrl: 'https://flagcdn.com/w40/rs.png' },
    { code: '+', name: 'Seychelles', flagUrl: 'https://flagcdn.com/w40/sc.png' },
    { code: '+', name: 'Sierra Leone', flagUrl: 'https://flagcdn.com/w40/sl.png' },
    { code: '+', name: 'Singapore', flagUrl: 'https://flagcdn.com/w40/sg.png' },
    { code: '+', name: 'Sint Maarten', flagUrl: 'https://flagcdn.com/w40/sx.png' },
    { code: '+', name: 'Slovakia', flagUrl: 'https://flagcdn.com/w40/sk.png' },
    { code: '+', name: 'Slovenia', flagUrl: 'https://flagcdn.com/w40/si.png' },
    { code: '+', name: 'Solomon Islands', flagUrl: 'https://flagcdn.com/w40/sb.png' },
    { code: '+', name: 'Somalia', flagUrl: 'https://flagcdn.com/w40/so.png' },
    { code: '+', name: 'South Africa', flagUrl: 'https://flagcdn.com/w40/za.png' },
    { code: '+', name: 'South Korea', flagUrl: 'https://flagcdn.com/w40/kr.png' },
    { code: '+', name: 'South Sudan', flagUrl: 'https://flagcdn.com/w40/ss.png' },
    { code: '+', name: 'Spain', flagUrl: 'https://flagcdn.com/w40/es.png' },
    { code: '+', name: 'Sri Lanka', flagUrl: 'https://flagcdn.com/w40/lk.png' },
    { code: '+', name: 'Sudan', flagUrl: 'https://flagcdn.com/w40/sd.png' },
    { code: '+', name: 'Suriname', flagUrl: 'https://flagcdn.com/w40/sr.png' },
    { code: '+', name: 'Svalbard and Jan Mayen', flagUrl: 'https://flagcdn.com/w40/sj.png' },
    { code: '+', name: 'Swaziland', flagUrl: 'https://flagcdn.com/w40/sz.png' },
    { code: '+', name: 'Sweden', flagUrl: 'https://flagcdn.com/w40/se.png' },
    { code: '+', name: 'Switzerland', flagUrl: 'https://flagcdn.com/w40/ch.png' },
    { code: '+', name: 'Taiwan', flagUrl: 'https://flagcdn.com/w40/tw.png' },
    { code: '+', name: 'Tajikistan', flagUrl: 'https://flagcdn.com/w40/tj.png' },
    { code: '+', name: 'Tanzania', flagUrl: 'https://flagcdn.com/w40/tz.png' },
    { code: '+', name: 'Thailand', flagUrl: 'https://flagcdn.com/w40/th.png' },
    { code: '+', name: 'Togo', flagUrl: 'https://flagcdn.com/w40/tg.png' },
    { code: '+', name: 'Tokelau', flagUrl: 'https://flagcdn.com/w40/tk.png' },
    { code: '+', name: 'Tonga', flagUrl: 'https://flagcdn.com/w40/to.png' },
    { code: '+', name: 'Trinidad and Tobago', flagUrl: 'https://flagcdn.com/w40/tt.png' },
    { code: '+', name: 'Tunisia', flagUrl: 'https://flagcdn.com/w40/tn.png' },
    { code: '+', name: 'Turkey', flagUrl: 'https://flagcdn.com/w40/tr.png' },
    { code: '+', name: 'Turkmenistan', flagUrl: 'https://flagcdn.com/w40/tm.png' },
    { code: '+', name: 'Turks and Caicos Islands', flagUrl: 'https://flagcdn.com/w40/tc.png' },
    { code: '+', name: 'Tuvalu', flagUrl: 'https://flagcdn.com/w40/tv.png' },
    { code: '+1', name: 'U.S.A', flagUrl: 'https://flagcdn.com/w40/us.png' },
    { code: '+1', name: 'U.S. Virgin Islands', flagUrl: 'https://flagcdn.com/w40/vi.png' },
    { code: '+', name: 'Uganda', flagUrl: 'https://flagcdn.com/w40/ug.png' },
    { code: '+', name: 'Ukraine', flagUrl: 'https://flagcdn.com/w40/ua.png' },
    { code: '+', name: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/w40/ae.png' },
    { code: '+44', name: 'United Kingdom', flagUrl: 'https://flagcdn.com/w40/gb.png' },
    { code: '+', name: 'United States', flagUrl: 'https://flagcdn.com/w40/us.png' },
    { code: '+', name: 'Uruguay', flagUrl: 'https://flagcdn.com/w40/uy.png' },
    { code: '+', name: 'Uzbekistan', flagUrl: 'https://flagcdn.com/w40/uz.png' },
    { code: '+', name: 'Vanuatu', flagUrl: 'https://flagcdn.com/w40/vu.png' },
    { code: '+', name: 'Vatican', flagUrl: 'https://flagcdn.com/w40/va.png' },
    { code: '+', name: 'Venezuela', flagUrl: 'https://flagcdn.com/w40/ve.png' },
    { code: '+', name: 'Vietnam', flagUrl: 'https://flagcdn.com/w40/vn.png' },
    { code: '+', name: 'Wallis and Futuna', flagUrl: 'https://flagcdn.com/w40/wf.png' },
    { code: '+', name: 'Western Sahara', flagUrl: 'https://flagcdn.com/w40/eh.png' },
    { code: '+', name: 'Yemen', flagUrl: 'https://flagcdn.com/w40/ye.png' },
    { code: '+', name: 'Zambia', flagUrl: 'https://flagcdn.com/w40/zm.png' },
    { code: '+', name: 'Zimbabwe', flagUrl: 'https://flagcdn.com/w40/zw.png' },


    { code: '+44', name: 'UK', flagUrl: 'https://flagcdn.com/w40/gb.png' },
    { code: '+91', name: 'India', flagUrl: 'https://flagcdn.com/w40/in.png' },
    { code: '+65', name: 'Singapore', flagUrl: 'https://flagcdn.com/w40/sg.png' },
    { code: '+60', name: 'Malaysia', flagUrl: 'https://flagcdn.com/w40/my.png' },
    { code: '+64', name: 'New Zealand', flagUrl: 'https://flagcdn.com/w40/nz.png' },
    { code: '+66', name: 'Thailand', flagUrl: 'https://flagcdn.com/w40/th.png' },
    { code: '+62', name: 'Indonesia', flagUrl: 'https://flagcdn.com/w40/id.png' },
    { code: '+63', name: 'Philippines', flagUrl: 'https://flagcdn.com/w40/ph.png' },
    { code: '+84', name: 'Vietnam', flagUrl: 'https://flagcdn.com/w40/vn.png' },
    { code: '+81', name: 'Japan', flagUrl: 'https://flagcdn.com/w40/jp.png' },
    { code: '+82', name: 'South Korea', flagUrl: 'https://flagcdn.com/w40/kr.png' },
    { code: '+33', name: 'France', flagUrl: 'https://flagcdn.com/w40/fr.png' },
    { code: '+49', name: 'Germany', flagUrl: 'https://flagcdn.com/w40/de.png' },
    { code: '+39', name: 'Italy', flagUrl: 'https://flagcdn.com/w40/it.png' },
    { code: '+34', name: 'Spain', flagUrl: 'https://flagcdn.com/w40/es.png' },
    { code: '+31', name: 'Netherlands', flagUrl: 'https://flagcdn.com/w40/nl.png' },
    { code: '+47', name: 'Norway', flagUrl: 'https://flagcdn.com/w40/no.png' },
    { code: '+46', name: 'Sweden', flagUrl: 'https://flagcdn.com/w40/se.png' },
    { code: '+41', name: 'Switzerland', flagUrl: 'https://flagcdn.com/w40/ch.png' },
    { code: '+351', name: 'Portugal', flagUrl: 'https://flagcdn.com/w40/pt.png' },
    { code: '+30', name: 'Greece', flagUrl: 'https://flagcdn.com/w40/gr.png' },
    { code: '+90', name: 'Turkey', flagUrl: 'https://flagcdn.com/w40/tr.png' },
    { code: '+7', name: 'Russia', flagUrl: 'https://flagcdn.com/w40/ru.png' },
    { code: '+20', name: 'Egypt', flagUrl: 'https://flagcdn.com/w40/eg.png' },
    { code: '+27', name: 'South Africa', flagUrl: 'https://flagcdn.com/w40/za.png' },
    { code: '+92', name: 'Pakistan', flagUrl: 'https://flagcdn.com/w40/pk.png' },
    { code: '+971', name: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/w40/ae.png' },
    { code: '+974', name: 'Qatar', flagUrl: 'https://flagcdn.com/w40/qa.png' },
    { code: '+966', name: 'Saudi Arabia', flagUrl: 'https://flagcdn.com/w40/sa.png' },
    { code: '+972', name: 'Israel', flagUrl: 'https://flagcdn.com/w40/il.png' },
    { code: '+98', name: 'Iran', flagUrl: 'https://flagcdn.com/w40/ir.png' },
    { code: '+850', name: 'North Korea', flagUrl: 'https://flagcdn.com/w40/kp.png' },
    { code: '+598', name: 'Uruguay', flagUrl: 'https://flagcdn.com/w40/uy.png' }
  ];
  

export default countries;